config/routes.rb
InstrumentalSescBrasil::Application.routes.draw do

  constraints host: "passagemdesom.sesctv.org.br" do
    controller :home do
      get :sound_check_home, path: ""
      get :sound_check_list, path: "lista"
    end
  end

  root to: "home#index"

  controller :home do
    get :about_us, path: "projeto"
    get :privacy, path: "privacidade"
    get :live, path: "aovivo"
    get :search, path: "busca"
    get :live_status, :format => :json
    resources :live_transmissions, :only => [:show], :path => "aovivo"
  end

  resources :artists, path: 'artistas', only: [:index, :show] do
    collection do
      get 'letra/:letter', letter: /[A-aZ-z_]/, action: :index, as: :letter
      get :legacy, path: 'memoria'
      get :export
    end
    resources :events, only: [:show], path: "" do
      get ':song_id', :action => :song, :as => :song
    end
  end

  resources :playlists, :only => [:index] do
    get :search, path: 'busca', on: :collection
  end

  get 'radio_instrumental' => 'radio#show', as: 'radio'

  legacy_route = lambda { |request|
    request.params[:id] =~ /^\d{1,7}$/ && request.params[:format] =~ /^aspx$/i
  }

  get 'ui/show' => 'events#legacy_show', :constraints => legacy_route
  get 'ui/interview' => 'events#legacy_interview', :constraints => legacy_route
  get 'ui/videochat' => 'events#legacy_video_chat', :constraints => legacy_route
  get 'ui/artist' => 'artists#legacy_artist', :constraints => legacy_route

  controller :contact_form do
    get :contact_form, path: "contato"
    post :contact, path: "contato"
  end

  resources :subscribers, only: [:create]

  get 'auth/:provider/callback' => 'oauth#callback'
  get 'auth/failure' => 'oauth#failure'

  namespace :admin, path: 'ueber', as: :admin do
    root to: 'home#dashboard'

    get    'login' => 'authentication#login_form', as: :login
    post   'login' => 'authentication#login'
    delete 'logoff' => 'authentication#logoff'

    get 'instruments' => 'instruments#index', :format => :json
    get 'genres' => 'genres#index', :format => :json

    post 'sync_videos' => 'home#sync_videos'
    post 'clear_cache' => 'home#clear_cache'

    resources :features, except: :show
    resources :artists, :except => :show do
      collection do
        get :datatable, :format => :json
        get :typeahead, :format => :json
      end
    end

    resources :tv_features, :except => [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_schedule_items, :only => [:index] do
      get :datatable, :on => :collection, :format => :json
      get :import, :on => :collection
      post :import, :on => :collection, action: :upload
      post :clear, :on => :collection
    end

    resources :schedule_items do
      get :datatable, :on => :collection, :format => :json
    end

    resources :pdf_schedules, only: %w(index new create destroy) do
      get :datatable, :on => :collection, :format => :json
    end

    resources :events, only: [:edit, :update]

    resources :shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      get :typeahead, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :legacy_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :interviews, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :video_chats, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :legacy_tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :sound_checks, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :live_transmissions, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end
    resource :live_transmission_settings, :only => [:edit, :update]
  end
end

app/views/admin/_admin_form.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <strong><%= fa_icon 'warning', "Por favor corrija os seguintes erros:" %></strong>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end -%>
    </ul>
  </div>
<% end -%>

<% scope = local_assigns[:scope] %>

<%= form_for [:admin, scope, model].compact,
             :html => { class: 'form-horizontal', autocomplete: 'off' } do |f| %>

  <% field_options = local_assigns[:field_options] || {} %>

  <% attributes.each do |att| %>
    <div class="form-group <%= ('has-error' if model.errors[att].any?) %>">
      <%= f.label att, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.admin_field att, field_options[att.to_sym] || {} %>
      </div>
    </div>
  <% end -%>

  <div class="form-group">
    <hr />
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button type: 'submit', class: 'btn btn-success' do %>
        <%= fa_icon :save, "Salvar" %>
      <% end -%>
      <% if local_assigns[:extra_buttons] %>
        <%= raw local_assigns[:extra_buttons].join %>
      <% end -%>
      <%= link_to [:admin, scope, model.class.model_name.route_key].compact,
                  :class => 'btn btn-default' do %>
        <i class="glyphicon glyphicon-list"></i> Voltar à lista
      <% end -%>
      <% if model.persisted? %>
        <%= link_to [:admin, scope, model].compact,
                    :class => "btn btn-danger",
                    :method => :delete,
                    :style => "margin-left: 25px;",
                    :data => { :confirm => "Tem certeza que deseja apagar o #{model.class.model_name.human.downcase}?" } do %>
          <%= fa_icon 'trash-o', "Apagar" %>
        <% end -%>
      <% end -%>
    </div>
  </div>

<% end -%>

app/views/admin/_flash_messages.html.erb
<% if flash.any? %>
<div class="flash-messages">
  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key %>">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= markdown_t "flash.#{message}" %>
    </div>
  <% end -%>
</div>
<% end -%>

app/views/admin/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to "Instrumental SESC Brasil", admin_root_path, class: 'navbar-brand' %>
  </div>

  <% if authenticated? %>
  <ul class="nav navbar-top-links navbar-right">
    <li><%= link_to fa_icon('power-off', "Sair"), admin_logoff_path, method: :delete %></li>
  </ul>
  <% end -%>
</nav>

app/views/admin/_sidebar.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <%= link_to fa_icon(:dashboard, "Painel de Controle", fixed: true), admin_root_path %>
      </li>
      <li><%= link_to fa_icon(:music, "Artistas", fixed: true), admin_artists_path %></li>
      <li><%= link_to fa_icon(:microphone, "Shows", fixed: true), admin_shows_path %></li>
      <li><%= link_to fa_icon(:microphone, "Shows (memória)", fixed: true), admin_legacy_shows_path %></li>
      <li><%= link_to fa_icon(:microphone, "Entrevistas", fixed: true), admin_interviews_path %></li>
      <li><%= link_to fa_icon(:microphone, "Bate-Papos", fixed: true), admin_video_chats_path %></li>
      <li><%= link_to fa_icon(:microphone, "Programa Instrumental", fixed: true), admin_tv_shows_path %></li>
      <li><%= link_to fa_icon(:microphone, "Passagem de Som", fixed: true), admin_sound_checks_path %></li>
      <li><%= link_to fa_icon(:microphone, "Instrumental (memória)", fixed: true), admin_legacy_tv_shows_path %></li>
      <% if @home_page_menu_active %>
      <li class="active">
      <% else %>
      <li>
      <% end -%>
        <a href="#"><%= fa_icon(:home, "Home Page", fixed: true) %><span class="fa arrow"></span></a>
        <ul class="nav nav-second-level collapse">
          <li><%= link_to fa_icon('picture-o', "Estréias SescTV", fixed: true), admin_tv_features_path %></li>
          <li><%= link_to fa_icon('calendar', "Programação SescTV", fixed: true), admin_tv_schedule_items_path %></li>
          <li><%= link_to fa_icon('file-o', "Programação em PDF", fixed: true), admin_pdf_schedules_path %></li>
          <li><%= link_to fa_icon('calendar', "Agenda de Shows", fixed: true), admin_schedule_items_path %></li>
        </ul>
      </li>
      <li><%= link_to fa_icon('picture-o', "Destaques", fixed: true), admin_features_path %></li>
      <li><%= link_to fa_icon('film', "Transmissões ao vivo", fixed: true), admin_live_transmissions_path %></li>
    </ul>
    <%= render "flash_messages" %>
  </div>
</nav>