config/routes.rb
InstrumentalSescBrasil::Application.routes.draw do

  constraints host: "passagemdesom.sesctv.org.br" do
    controller :home do
      get :sound_check_home, path: ""
      get :sound_check_list, path: "lista"
    end
  end

  root to: "home#index"

  controller :home do
    get :about_us, path: "projeto"
    get :privacy, path: "privacidade"
    get :live, path: "aovivo"
    get :search, path: "busca"
    get :live_status, :format => :json
    resources :live_transmissions, :only => [:show], :path => "aovivo"
  end

  resources :artists, path: 'artistas', only: [:index, :show] do
    collection do
      get 'letra/:letter', letter: /[A-aZ-z_]/, action: :index, as: :letter
      get :legacy, path: 'memoria'
      get :export
    end
    resources :events, only: [:show], path: "" do
      get ':song_id', :action => :song, :as => :song
    end
  end

  resources :playlists, :only => [:index] do
    get :search, path: 'busca', on: :collection
  end

  get 'radio_instrumental' => 'radio#show', as: 'radio'

  legacy_route = lambda { |request|
    request.params[:id] =~ /^\d{1,7}$/ && request.params[:format] =~ /^aspx$/i
  }

  get 'ui/show' => 'events#legacy_show', :constraints => legacy_route
  get 'ui/interview' => 'events#legacy_interview', :constraints => legacy_route
  get 'ui/videochat' => 'events#legacy_video_chat', :constraints => legacy_route
  get 'ui/artist' => 'artists#legacy_artist', :constraints => legacy_route

  controller :contact_form do
    get :contact_form, path: "contato"
    post :contact, path: "contato"
  end

  resources :subscribers, only: [:create]

  get 'auth/:provider/callback' => 'oauth#callback'
  get 'auth/failure' => 'oauth#failure'

  namespace :admin, path: 'ueber', as: :admin do
    root to: 'home#dashboard'

    get    'login' => 'authentication#login_form', as: :login
    post   'login' => 'authentication#login'
    delete 'logoff' => 'authentication#logoff'

    get 'instruments' => 'instruments#index', :format => :json
    get 'genres' => 'genres#index', :format => :json

    post 'sync_videos' => 'home#sync_videos'
    post 'clear_cache' => 'home#clear_cache'

    resources :features, except: :show
    resources :artists, :except => :show do
      collection do
        get :datatable, :format => :json
        get :typeahead, :format => :json
      end
    end

    resources :tv_features, :except => [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_schedule_items, :only => [:index] do
      get :datatable, :on => :collection, :format => :json
      get :import, :on => :collection
      post :import, :on => :collection, action: :upload
      post :clear, :on => :collection
    end

    resources :schedule_items do
      get :datatable, :on => :collection, :format => :json
    end

    resources :pdf_schedules, only: %w(index new create destroy) do
      get :datatable, :on => :collection, :format => :json
    end

    resources :events, only: [:edit, :update]

    resources :shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      get :typeahead, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :legacy_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :interviews, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :video_chats, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :legacy_tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :sound_checks, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :live_transmissions, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end
    resource :live_transmission_settings, :only => [:edit, :update]
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def dashboard
  end

  def sync_videos
    run_rake('videos:sync', 'Vídeos sincronizando')
  end

  def clear_cache
    run_rake('tmp:cache:clear', 'Cache limpo')
  end

  private

  def run_rake(name, success_message)
    rake = "RAILS_ENV=#{Rails.env} bundle exec rake #{name} --trace &"
    Kernel.system(rake)

    flash[:success] = success_message
  rescue => e
    Rails.logger.error e.message
    flash[:error] = 'Não rolou'
  ensure
    redirect_to admin_root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
    @features = Feature.not_sound_check.enabled
  end

  # GET /projeto
  def about_us
  end

  # GET /passagem-de-som
  def sound_check_home
    @features = Feature.sound_check.enabled
  end

  # GET /passagem-de-som/lista
  def sound_check_list
    @events = SoundCheck.visible.order("date desc")
  end

  # GET /busca?q=....
  def search
    @search_term = params[:q]
    @search =
      SearchResult.search(@search_term)
                  .filtered_by_instrument(params[:instrument_id])
                  .filtered_by_genre(params[:genre_id])
    @artist_results = @search.artists.limit(15)
    @show_results = @search.shows.limit(9)
    @more_results = @search.more.limit(25)
  end

  # GET /privacidade
  def privacy
  end

  def live
    if @transmission = LiveTransmission.current
      redirect_to @transmission
    else
      redirect_to root_path
    end
  end

  def live_status
    render :json => LiveTransmission.live_status
  end

  private

  def search_params
    params.permit(:instrument_id, :genre_id)
  end

  def cache_key
    ["search-results", params.permit(:q, :instrument_id, :genre_id)]
  end
  helper_method :cache_key

end

app/helpers/home_helper.rb
module HomeHelper

  def about_us_feature_image
    title = t("home.about_us.title")
    image_tag("aboutus-feature.jpg",
              size: '900x600', class: 'round', alt: title)
  end

  def about_us_feature_image_soundcheck
    image_tag("passagem-de-som-projeto.jpg", size: '900x600', class: 'round', alt: "Passagem de Som")
  end

  def about_us_sescsp_link
    title = t('links.sescsp.title')
    url = t('links.sescsp.url')
    image = image_tag("aboutus-logo-sescsp.jpg", size: '290x130',
                      class: 'round', alt: 'title')
    link_to image, url, target: '_blank', title: title
  end

  def about_us_sesctv_link
    title = t('links.sesctv.title')
    url = t('links.sesctv.url')
    image = image_tag("aboutus-logo-sesctv.jpg", size: '290x130',
                      class: 'round', alt: 'title')
    link_to image, url, target: '_blank', title: title
  end

end

app/views/home/_artist.html.erb
<% cache artist do %>
<div class="artist-thumbnail">
  <%= link_to artist do %>
    <%= image_tag(artist.thumbnail_url, size: '200x200',
                  alt: artist.name, class: 'round') %>
    <span><%= artist.name %></span>
  <% end -%>
</div>
<% end -%>

app/views/home/_artists.html.erb
<% cache "home-artists", :expires_in => 30.minutes do %>
<div class="block home-artists">
  <div class="home-artists-list">
    <%= link_to "ver todos os artistas", artists_path, :class => "btn-orange" %>
    <h2>Lista de Artistas</h2>
    <%= render "artists_table", artists: Artist.visible.random(4), :row_size => 4 %>
  </div>
  <div class="top-ten">
    <h2>Top 10</h2>
    <div class="top-ten-list">
      <h3>Artistas</h3>
      <% Artist.visible.top(10).each_with_index.to_a.in_groups_of(5) do |artists| %>
        <ul>
          <% artists.each do |artist, i| %>
            <li><strong><%= i + 1 %>. </strong><%= link_to artist.name, artist %></li>
          <% end -%>
        </ul>
      <% end -%>
    </div>
    <div class="top-ten-list">
      <h3>Músicas</h3>
      <% Song.top(10).each_with_index.to_a.in_groups_of(5) do |songs| %>
        <ul>
          <% songs.each do |song, i| %>
            <li><strong><%= i + 1 %>. </strong>
            <%= link_to song.title, artist_event_path(
                                      song.artist, song.playlistable,
                                      :video_id => song.video.youtube_id) %></li>
          <% end -%>
        </ul>
      <% end -%>
    </div>
  </div>
</div>
<% end -%>

app/views/home/_events_table.html.erb
<table class="artists-grid">
  <% row_size = local_assigns[:row_size] || 3 %>
  <%= events.in_groups_of(row_size, false) do |events| %>
  <tr>
    <% events.each_with_index do |event, i| %>
      <%= content_tag :td, render(event), class: ('last' if i == (row_size - 1)) %>
    <% end -%>
  </tr>
  <% end -%>
</table>

app/views/home/_features.html.erb
<% cache [request.host, "home-page-features"], expires_in: 15.minutes, skip_digest: true do %>
<% if features.any? %>
<div class="feature">
  <div class="feature-carousel">
    <ul>
      <% features.each do |feature| %>
      <%= content_tag :li, :data => {
                        :description => markdown(feature.description),
                        :title => feature.title
                      } do %>
        <%= link_to feature.url, title: feature.title do %>
          <%= image_tag feature.banner.url,
                        :class => 'round',
                        :title => feature.title,
                        :width => feature.banner_width,
                        :height => feature.banner_height,
                        :alt => feature.title %>
        <% end -%>
      <% end -%>
      <% end -%>
    </ul>
  </div>
  <div class="feature-sidebar">
    <div class="block main-feature-block">
      <%= link_to features[0].url, title: features[0].title do %>
        <h1 id="feature-carousel-title"><%= features[0].title %></h1>
        <div id="feature-carousel-description">
          <%= markdown features[0].description %>
        </div>
      <% end -%>
    </div>
  </div>
</div>
<% end -%>
<% end -%>

app/views/home/_programs.html.erb
<div class="block home-artists">
  <div class="home-artists-list">
    <%= link_to "ver todos os programas", sound_check_list_path, :class => "btn-orange" %>
    <h2>Lista de Programas</h2>
    <%= render "events_table", events: SoundCheck.visible.random(4), :row_size => 4 %>
  </div>
</div>

app/views/home/_schedule.html.erb
<div class="home-schedule">

  <div class="home-tv-schedule">
    <div class="events-list-title events-list-title-tv">
      <h2>Programação no canal SescTV</h2>
    </div>

    <% cache "tv-features-homepage", skip_digest: true do %>
      <div class="block">
        <% if @tv_feature = TvFeature.current %>
          <%= link_to artist_event_path(@tv_feature.show.artist, @tv_feature.show) do %>
            <h3>Próxima estréia do palco para a televisão</h3>
            <div class="debut-image">
              <%= artist_thumbnail(@tv_feature.artist) %>
              <h4><%= @tv_feature.artist.name %></h4>
              <h5><span><%= l @tv_feature.debuts_at, format: :brief %></span></h5>
            </div>
            <div class="debut-description">
              <%= markdown @tv_feature.description %>
            </div>
          <% end -%>
        <% end -%>
      </div>
    <% end -%>

    <% cache "tv-schedule-homepage-current-item-#{Date.current.to_s}", skip_digest: true do %>
      <% if schedule_day = TvScheduleItem.current_or_last_day %>
        <div class="home-tv-schedule-feed">
          <h4>Veja a programação para o dia <%= l schedule_day, format: :short %></h4>
          <ul>
            <% TvScheduleItem.for_day(schedule_day).each do |schedule_item| %>
            <li>
              <span><%= l schedule_item.starts_at, format: :time %></span><%= schedule_item.description %>
            </li>
            <% end -%>
          </ul>
        </div>
      <% end -%>
    <% end -%>

  </div>

  <% cache "schedule-items-homepage-#{Date.current.to_s}", skip_digest: true do %>
  <div class="home-site-schedule tabstrip">
    <div class="home-site-schedule-title">
      <h2>No palco do Sesc Consolação e ao vivo na Internet</h2>
      <h3>Toda segunda-feira, às 19h</h3>
    </div>
    <%
      items = ScheduleItem.current_items
      closest = closest_schedule_item(items)
    %>
    <div class="schedule-tabs">
      <nav>
        <% items.each do |item| %>
          <%= home_schedule_tab(item, closest == item) %>
        <% end -%>
      </nav>
    </div>
    <% items.each do |item| %>
      <%= home_schedule_panel(item, closest == item) do %>
        <div class="schedule-tab-thumb">
          <%= artist_thumbnail(item.artist) %>
          <h5><%= item.artist.name %></h5>
        </div>
        <div class="schedule-tab-description">
          <%= markdown item.description %>
        </div>
      <% end -%>
    <% end -%>
    <% cache "pdf-schedule-homepage-#{Date.current.to_s}", skip_digest: true do %>
      <% if pdf_schedule = PdfSchedule.current %>
        <div class="schedule-pdf">
          <%= link_to pdf_schedule.file.url, :target => "_blank" do %>
            <%= image_tag("icon-pdf.png", :size => "36x33", :align => :absmiddle) %> Clique para ver a programação completa
          <% end -%>
        </div>
      <% end -%>
    <% end -%>
  </div>
  <% end -%>

</div>

app/views/home/_sound_check_schedule.html.erb
<div class="home-schedule soundcheck">

  <div class="home-tv-schedule">
    <div class="events-list-title events-list-title-tv">
      <h2>Programação no canal SescTV</h2>
    </div>

    <% cache "tv-features-homepage", skip_digest: true do %>
      <div class="block">
        <% if @tv_feature = TvFeature.current %>
          <%= link_to artist_event_path(@tv_feature.show.artist, @tv_feature.show) do %>
            <h3>Próxima estréia do palco para a televisão</h3>
            <div class="debut-image">
              <%= artist_thumbnail(@tv_feature.artist) %>
              <h4><%= @tv_feature.artist.name %></h4>
              <h5><span><%= l @tv_feature.debuts_at, format: :brief %></span></h5>
            </div>
            <div class="debut-description">
              <%= markdown @tv_feature.description %>
            </div>
          <% end -%>
        <% end -%>
      </div>
    <% end -%>

    <% cache "tv-schedule-homepage-current-item-#{Date.current.to_s}", skip_digest: true do %>
      <% if schedule_day = TvScheduleItem.current_or_last_day %>
        <div class="home-tv-schedule-feed">
          <h4>Veja a programação para o dia <%= l schedule_day, format: :short %></h4>
          <ul>
            <% TvScheduleItem.for_day(schedule_day).each do |schedule_item| %>
            <li>
              <span><%= l schedule_item.starts_at, format: :time %></span><%= schedule_item.description %>
            </li>
            <% end -%>
          </ul>
        </div>
      <% end -%>
    <% end -%>

  </div>

  <%# cache "schedule-items-homepage-#{Date.current.to_s}", skip_digest: true do %>
  <div class="home-site-schedule tabstrip">
    <div class="home-site-schedule-title">
      <h2>Próximas Estréias</h2>
      <h3>Todo domingo às 21:30</h3>
    </div>
    <%
      items = TvFeature.current_items
      closest = closest_tv_feature_item(items)
    %>
    <div class="schedule-tabs">
      <nav>
        <% items.each do |item| %>
          <%= home_tv_feature_tab(item, closest == item) %>
        <% end -%>
      </nav>
    </div>
    <% items.each do |item| %>
      <%= home_tv_feature_panel(item, closest == item) do %>
        <div class="schedule-tab-thumb">
          <%= artist_thumbnail(item.artist) %>
          <h5><%= item.artist.name %></h5>
        </div>
        <div class="schedule-tab-description">
          <%= markdown item.description %>
        </div>
      <% end -%>
    <% end -%>
  </div>
  <%# end -%>

</div>

app/views/home/about_us.html.erb
<% title t(".title") %>

<%# cache [request.host, "about-us"] do %>

  <% if sound_check_domain? %>
    <div class="feature">
      <%= about_us_feature_image_soundcheck %>
      <div class="feature-sidebar">
        <h1 class="feature-title">Sobre</h1>
        <div class="block">
          <p>Passagem de Som é um programa documental que narra os bastidores da criação musical, contando com depoimentos de compositores e músicos que participam do Instrumental Sesc Brasil.</p>
          <p><%= link_to "veja a lista", sound_check_list_path, class: 'btn-red' %></p>
        </div>
      </div>
    </div>

  <% else -%>

    <div class="feature">
      <%= about_us_feature_image %>
      <div class="feature-sidebar">
        <h1 class="feature-title"><%= t ".title" %></h1>
        <div class="block">
          <%= markdown_t ".content" %>
        </div>
      </div>
    </div>

    <div class="aboutus-credits">
      <div class="block-title block-title-orange">
        <h2><%= t ".credits.title" %></h2>
      </div>
      <div class="block">
        <%= markdown_t ".credits.content" %>
      </div>
    </div>

    <div class="aboutus-mention">
      <div class="block-title block-title-orange">
        <h2><%= t ".mention.title" %></h2>
      </div>
      <div class="block">
        <%= markdown_t ".mention.content" %>
      </div>
      <nav class="aboutus-nav">
        <%= about_us_sescsp_link %>
        <%= about_us_sesctv_link %>
      </nav>
    </div>

  <% end -%>

<%# end -%>

app/views/home/index.html.erb
<%= render "features", features: @features %>
<%= render "schedule" %>
<%= render "artists" %>

app/views/home/privacy.html.erb
<% title t(".title") %>

<% cache do %>
<div class="block-title">
  <h1><%= t ".title" %></h1>
</div>
<div class="block">
  <%= markdown_t ".content" %>
</div>
<% end -%>

app/views/home/search.html.erb
<% title t(".title") %>

<% cache cache_key, expires_in: 5.minutes do %>

<div class="search-results-sidebar">
  <div class="block search-filters">
    <h2>Filtrar Busca</h2>
    <%= render "search_filters", :scope => @search %>
  </div>
</div>

<div class="search-results-block">
  <div class="block-title">
    <h1>Busca</h1>
  </div>
  <div class="block">
    <div class="summary">
      <h2>Resultados para o termo:</h2>
      <p><%= @search_term %></p>
    </div>

    <% if @search.empty? %>
      <p>Nenhum resultado encontrado.</p>
    <% end -%>

    <% if @artist_results.any? %>
      <h2>Artistas</h2>
      <%= render "artists_table", artists: @artist_results.map(&:searchable) %>
    <% end -%>

    <% if @show_results.any? %>
      <h2>Shows</h2>
      <%= render "videos_list", events: @show_results.map(&:searchable), title_method: :title %>
    <% end-%>

    <% if @more_results.any? %>
      <h2>Outros resultados</h2>
      <%= render "videos_list", events: @more_results.map(&:searchable), title_method: :title %>
    <% end-%>
  </div>
</div>

<% end -%>

app/views/home/sound_check_home.html.erb
<%= render "features", features: @features %>
<%= render "sound_check_schedule" %>
<%= render "programs" %>

app/views/home/sound_check_list.html.erb
<div class="whiteblock sound-check-list">
  <ul>
  <% @events.each do |event| %>
    <li>
      <div class="thumb">
        <%= image_tag(event.artist.thumbnail_url, size: '200x200',
              alt: event.artist.name, class: 'round') %>
      </div>
      <div class="description">
        <h2><%= event.artist.name %><small><%= l(event.date) %></small></h2>
        <%= markdown event.description %>
        <p>
          <%= link_to "assistir programa", artist_event_path(event.artist, event), class: "btn-red" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "perfil do artista", artist_path(event.artist), class: 'btn-grey' %>
        </p>
      </div>
    </li>
  <% end -%>
  </ul>
</div>