config/routes.rb
InstrumentalSescBrasil::Application.routes.draw do

  constraints host: "passagemdesom.sesctv.org.br" do
    controller :home do
      get :sound_check_home, path: ""
      get :sound_check_list, path: "lista"
    end
  end

  root to: "home#index"

  controller :home do
    get :about_us, path: "projeto"
    get :privacy, path: "privacidade"
    get :live, path: "aovivo"
    get :search, path: "busca"
    get :live_status, :format => :json
    resources :live_transmissions, :only => [:show], :path => "aovivo"
  end

  resources :artists, path: 'artistas', only: [:index, :show] do
    collection do
      get 'letra/:letter', letter: /[A-aZ-z_]/, action: :index, as: :letter
      get :legacy, path: 'memoria'
      get :export
    end
    resources :events, only: [:show], path: "" do
      get ':song_id', :action => :song, :as => :song
    end
  end

  resources :playlists, :only => [:index] do
    get :search, path: 'busca', on: :collection
  end

  get 'radio_instrumental' => 'radio#show', as: 'radio'

  legacy_route = lambda { |request|
    request.params[:id] =~ /^\d{1,7}$/ && request.params[:format] =~ /^aspx$/i
  }

  get 'ui/show' => 'events#legacy_show', :constraints => legacy_route
  get 'ui/interview' => 'events#legacy_interview', :constraints => legacy_route
  get 'ui/videochat' => 'events#legacy_video_chat', :constraints => legacy_route
  get 'ui/artist' => 'artists#legacy_artist', :constraints => legacy_route

  controller :contact_form do
    get :contact_form, path: "contato"
    post :contact, path: "contato"
  end

  resources :subscribers, only: [:create]

  get 'auth/:provider/callback' => 'oauth#callback'
  get 'auth/failure' => 'oauth#failure'

  namespace :admin, path: 'ueber', as: :admin do
    root to: 'home#dashboard'

    get    'login' => 'authentication#login_form', as: :login
    post   'login' => 'authentication#login'
    delete 'logoff' => 'authentication#logoff'

    get 'instruments' => 'instruments#index', :format => :json
    get 'genres' => 'genres#index', :format => :json

    post 'sync_videos' => 'home#sync_videos'
    post 'clear_cache' => 'home#clear_cache'

    resources :features, except: :show
    resources :artists, :except => :show do
      collection do
        get :datatable, :format => :json
        get :typeahead, :format => :json
      end
    end

    resources :tv_features, :except => [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_schedule_items, :only => [:index] do
      get :datatable, :on => :collection, :format => :json
      get :import, :on => :collection
      post :import, :on => :collection, action: :upload
      post :clear, :on => :collection
    end

    resources :schedule_items do
      get :datatable, :on => :collection, :format => :json
    end

    resources :pdf_schedules, only: %w(index new create destroy) do
      get :datatable, :on => :collection, :format => :json
    end

    resources :events, only: [:edit, :update]

    resources :shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      get :typeahead, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :legacy_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :interviews, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :video_chats, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :legacy_tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :sound_checks, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :live_transmissions, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end
    resource :live_transmission_settings, :only => [:edit, :update]
  end
end

app/models/tv_schedule_item.rb
require 'csv'

class TvScheduleItem < ActiveRecord::Base
  validates_presence_of :starts_at, :description

  class << self
    def current_or_last_day
      where("date_trunc('day', starts_at) <= ?", Date.current)
        .maximum("date_trunc('day', starts_at)").try :to_date
    end

    def for_day(day)
      where("date_trunc('day', starts_at) = ?", day.to_date).order(:starts_at)
    end

    def import(file)
      rows = CSV.read(file)
      total_imported = 0

      transaction do
        rows.each_with_index do |row, i|
          description = row.pop.strip
          starts_at = Time.parse(row.join(' ').strip)
          item = where(starts_at: starts_at).first_or_initialize(description: description)
          total_imported += 1 if item.save
        end
      end

      total_imported
    end
  end
end

app/controllers/admin/tv_schedule_items_controller.rb
class Admin::TvScheduleItemsController < AdminController
  def index
  end

  def datatable
    @tv_schedule_items = TvScheduleItem.all
  end

  def import
  end

  def upload
    if params[:file].blank?
      flash[:warning] = "admin.tv_schedule_items.no_import"
      redirect_to import_admin_tv_schedule_items_path
      return
    end

    total = TvScheduleItem.import(params[:file].path)

    if total > 0
      invalidate_cache
      flash[:success] = "admin.tv_schedule_items.import"
    else
      flash[:warning] = "admin.tv_schedule_items.no_import"
    end

    redirect_to admin_tv_schedule_items_path
  end

  def clear
    TvScheduleItem.delete_all
    invalidate_cache
    flash[:success] = "admin.tv_schedule_items.clear"
    redirect_to admin_tv_schedule_items_path
  end

  private

  def invalidate_cache
    expire_fragment("tv-schedule-homepage-current-item-#{Date.current.to_s}")
    expire_fragment("tv-schedule-footer-feed-#{Date.current.to_s}")
  end
end

app/views/admin/tv_schedule_items/import.html.erb
<% @home_page_menu_active = true %>
<h1 class="page-header">Home Page - Programação SescTV</h1>
<div style="margin-bottom: 15px;">
  <%= link_to "Voltar à lista", admin_tv_schedule_items_path, class: "btn btn-default" %>
</div>
<div class="panel panel-default">
  <div class="panel-heading">Importar arquivo CSV</div>
  <div class="panel-body">
    <div class="alert alert-info">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <p>
        <%= fa_icon "info-circle" %>
        Cada linha do arquivo CSV deve ter 3 colunas, separadas por vírgula (,):
        <ul>
            <li>data (DD/MM/AAAA)</li>
            <li>hora (HH:MM:SS)</li>
            <li>nome do programa</li>
        </ul>
      </p>
      <p>
        Por exemplo:<br>
        31/05/2015, 13:45:00, Instrumental SESC Brasil - Pedro Bonamides
      </p>
      <p>
        Caso alguma linha contenha data ou hora com formato inválido, com o nome do programa faltando, essa linha será ignorada.
      </p>
    </div>
    <%= form_tag import_admin_tv_schedule_items_path, :class => "form-horizontal", :multipart => true do %>
      <div class="form-group">
        <label for="file" class="control-label col-sm-2">Arquivo</label>
        <div class="col-sm-10">
          <%= file_field_tag :file, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Importar</button>
        </div>
      </div>
    <% end -%>
  </div>
</div>

app/views/admin/tv_schedule_items/index.html.erb
<% @home_page_menu_active = true %>
<h1 class="page-header">Home Page - Programação SescTV</h1>
<div style="margin-bottom: 15px;">
  <%= link_to "Importar arquivo CSV", import_admin_tv_schedule_items_path, class: "btn btn-primary" %>
  <%= link_to "Apagar todos os itens", clear_admin_tv_schedule_items_path,
              :method => :post, :class => 'btn btn-danger',
              :data => { :confirm => "Tem certeza que deseja apagar TODOS os itens abaixo?" } %>
</div>
<div class="panel panel-default">
  <div class="panel-heading">Programação do SescTV</div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-condensed table-hover" id="tv-schedule-items-table">
        <thead>
          <tr>
            <th>Data / hora</th>
            <th>Programa</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
jQuery(function($) {

  $("#tv-schedule-items-table").dataTable({
    "bProcessing": true,
    "bAutoWidth": false,
    "sAjaxSource": "/ueber/tv_schedule_items/datatable.json",
    "aoColumns": [
      { "iDataSort":  2, "sWidth": "150px" },
      { "bSortable": false },
      { "bVisible": false }
    ],
    "aaSorting": [[0,'desc']]
  });

});
</script>