config/routes.rb
InstrumentalSescBrasil::Application.routes.draw do

  constraints host: "passagemdesom.sesctv.org.br" do
    controller :home do
      get :sound_check_home, path: ""
      get :sound_check_list, path: "lista"
    end
  end

  root to: "home#index"

  controller :home do
    get :about_us, path: "projeto"
    get :privacy, path: "privacidade"
    get :live, path: "aovivo"
    get :search, path: "busca"
    get :live_status, :format => :json
    resources :live_transmissions, :only => [:show], :path => "aovivo"
  end

  resources :artists, path: 'artistas', only: [:index, :show] do
    collection do
      get 'letra/:letter', letter: /[A-aZ-z_]/, action: :index, as: :letter
      get :legacy, path: 'memoria'
      get :export
    end
    resources :events, only: [:show], path: "" do
      get ':song_id', :action => :song, :as => :song
    end
  end

  resources :playlists, :only => [:index] do
    get :search, path: 'busca', on: :collection
  end

  get 'radio_instrumental' => 'radio#show', as: 'radio'

  legacy_route = lambda { |request|
    request.params[:id] =~ /^\d{1,7}$/ && request.params[:format] =~ /^aspx$/i
  }

  get 'ui/show' => 'events#legacy_show', :constraints => legacy_route
  get 'ui/interview' => 'events#legacy_interview', :constraints => legacy_route
  get 'ui/videochat' => 'events#legacy_video_chat', :constraints => legacy_route
  get 'ui/artist' => 'artists#legacy_artist', :constraints => legacy_route

  controller :contact_form do
    get :contact_form, path: "contato"
    post :contact, path: "contato"
  end

  resources :subscribers, only: [:create]

  get 'auth/:provider/callback' => 'oauth#callback'
  get 'auth/failure' => 'oauth#failure'

  namespace :admin, path: 'ueber', as: :admin do
    root to: 'home#dashboard'

    get    'login' => 'authentication#login_form', as: :login
    post   'login' => 'authentication#login'
    delete 'logoff' => 'authentication#logoff'

    get 'instruments' => 'instruments#index', :format => :json
    get 'genres' => 'genres#index', :format => :json

    post 'sync_videos' => 'home#sync_videos'
    post 'clear_cache' => 'home#clear_cache'

    resources :features, except: :show
    resources :artists, :except => :show do
      collection do
        get :datatable, :format => :json
        get :typeahead, :format => :json
      end
    end

    resources :tv_features, :except => [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_schedule_items, :only => [:index] do
      get :datatable, :on => :collection, :format => :json
      get :import, :on => :collection
      post :import, :on => :collection, action: :upload
      post :clear, :on => :collection
    end

    resources :schedule_items do
      get :datatable, :on => :collection, :format => :json
    end

    resources :pdf_schedules, only: %w(index new create destroy) do
      get :datatable, :on => :collection, :format => :json
    end

    resources :events, only: [:edit, :update]

    resources :shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      get :typeahead, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :legacy_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
      resources :songs, :except => :show do
        post :reorder, :on => :collection
      end
    end

    resources :interviews, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :video_chats, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :legacy_tv_shows, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :sound_checks, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end

    resources :live_transmissions, except: [:show] do
      get :datatable, :on => :collection, :format => :json
    end
    resource :live_transmission_settings, :only => [:edit, :update]
  end
end

app/models/playlist.rb
class Playlist

  def initialize(songs)
    @songs = songs
  end

  def songs
    @songs ||= []
  end

  def self.load_from_cookie(cookie)
    song_ids = (cookie || "").split("|")
    songs = song_ids.map do |id|
      Song.find_by_id(id)
    end
    Playlist.new(songs.compact)
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  # GET /playlists
  def index
    @playlist = Playlist.load_from_cookie(request.cookies['instrumental-playlist'])
  end

  # GET /playlists/busca?q=foo
  def search
    query = params[:q].try(:strip)
    if query && query.length > 0
      @songs = Song.search(query).order("artists.name, songs.title").limit(50)
    else
      @songs = []
    end
  end

end

app/views/playlists/_search_result.html.erb
<%
  genres = song.genres.to_a.map(&:name).to_sentence
  genre_list = genres == "" ? "-" : genres
  instruments = song.instruments.to_a.map(&:name).to_sentence
  instrument_list = instruments == "" ? "-" : instruments
%>

<tr>
  <td><%= song.title_with_composer %></td>
  <td><%= song.artist.name %></td>
  <td><%= genre_list %></td>
  <td><%= instrument_list %></td>
  <td>
    <%= link_to image_tag("playlist-add.jpg", alt: "+", title: "Adicionar à Playlist"), '#',
                :class => 'playlist-add',
                :data => {
                  :song_id => song.id,
                  :item => render("song", :song => song).to_json
                } %>
  </td>
</tr>

app/views/playlists/_song.html.erb
<li>
  <a href='#' class='playlist-item' data-id='<%= song.id %>' data-video='<%= song.video.youtube_id %>'>
    <h3><%= song.title %></h3>
    <p>
      <small><%= song.artist.name %></small>
    </p>
  </a>
  <a href='#' class='playlist-delete' data-id='<%= song.id %>'>
    <%= image_tag("playlist-delete.jpg", alt: "x") %>
  </a>
</li>

app/views/playlists/index.html.erb
<div class="playlist">
  <div class="block-title">
    <h1>Acervo de vídeos</h1>
  </div>
  <div class="whiteblock grid">
    <div class="col col-70">
      <div class="video-player" id="playlist-player"></div>
    </div>
    <div class="col col-30 playlist-sidebar">
      <h2>Minha Playlist</h2>
      <ul class="playlist-list">
        <%= render :partial => "song", collection: @playlist.songs %>
      </ul>
      <%= link_to "apagar lista", "#",
                  :class => "clear-playlist btn-green",
                  :style => (@playlist.songs.any? ? "display: inline-block;" : "display: none;"),
                  :confirm => "Tem certeza?" %>
    </div>
  </div>


  <div class="grid" style="margin-top: 25px;">
    <div class="col col-70">
      <div class="whiteblock playlist-search">
        <h2>Buscar vídeos</h2>
        <%= form_tag search_playlists_path, :remote => true, :method => :get do %>
          <input type="text" name="q" placeholder="Digite o nome do artista ou da música" autocomplete="off">
          <input type="submit" value="ok">
        <% end -%>
        <hr />
        <p><small>Clique no + para adicionar uma música em sua playlist</small></p>
        <table id="playlist-search-results">
          <thead>
            <tr>
              <th>Música</th>
              <th>Artista</th>
              <th>Gênero</th>
              <th colspan="2">Instrumento</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col col-30">
      <div class="whiteblock playlists-instrumental">
        <h2>Playlists Instrumental</h2>
        <hr />
      </div>
    </div>
  </div>
</div>

app/views/playlists/search.js.erb
tbody = $("#playlist-search-results tbody");
tbody.find("tr").remove();

<% results = @songs.map { |song| render('search_result', song: song) } %>
tbody.append("<%= j raw results.join %>");